// Channel actions
export const OPEN_CHANNEL = "OPEN_CHANNEL";
export const REQUEST_CHANNEL_CLOSE = "REQUEST_CHANNEL_CLOSE";
export const SET_CHANNEL_CLOSED = "SET_CHANNEL_CLOSED";
export const SET_CHANNEL_SETTLED = "SET_CHANNEL_SETTLED";

// Deposit actions

export const NEW_DEPOSIT = "NEW_DEPOSIT";

// Payment actions

export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const ADD_PENDING_PAYMENT_MESSAGE = "ADD_PENDING_PAYMENT_MESSAGE";
export const DELETE_ALL_PENDING_PAYMENTS = "DELETE_ALL_PENDING_PAYMENTS";

// Polling actions

export const MESSAGE_POLLING = "MESSAGE_POLLING";
export const MESSAGE_SENT = "MESSAGE_SENT";
