export const PENDING_PAYMENT = "PENDING";
export const FAILED_PAYMENT = "FAILED";
export const COMPLETED_PAYMENT = "COMPLETED";

export const EXPIRED = "EXPIRED";
export const REFUND_TRANSFER = "REFUND_TRANSFER";

export const FAILURE_REASONS = {
  [EXPIRED]: EXPIRED,
  [REFUND_TRANSFER]: REFUND_TRANSFER,
};
